security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        auth:
            entity: {
                class: App\Entity\User,
                property: username
            }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider: auth
            form_login:
                login_path: app-login
                check_path: app-login
                default_target_path: app-login
                username_parameter: username
                password_parameter: password
            logout:
                path: app-logout
                target: app-login
    access_control:
        - { path: ^/admin/users, roles: ROLE_ADMIN }
